export { default as LandingCTASection } from "./LandingCTASection";
export { default as LandingFAQSection } from "./LandingFAQSection";
export { default as LandingHeroSection } from "./LandingHeroSection";
export { default as LandingHowItWorksSection } from "./LandingHowItWorksSection";
export { default as LandingPopularCoursesSection } from "./LandingPopularCoursesSection";
export { default as LandingSkillsSection } from "./LandingSkillsSection";
export { default as LandingTeachersSection } from "./LandingTeachersSection";
export { default as LandingTestimonialsSection } from "./LandingTestimonialsSection";
export { default as LandingWhyChooseUsSection } from "./LandingWhyChooseUsSection";
